### ISSUE TITLE
fetch-crl needs to be installed as well

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-arc-frontend#2]

**Comment by martbhell** [comment]
Already done in https://github.com/CSC-IT-Center-for-Science/ansible-role-arc-client 
Should be in this role too so that the roles don't depend on eachother.

**Comment by A1ve5** [comment]
fixed on 3d1a9d3c5a149d3ba2d1533fd2b52c855103f266
