### ISSUE TITLE
NIS db need to be updated after adding users 

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-arc-frontend#5]
[root@io-install ~]# make -C /var/yp

**Comment by martbhell** [comment]
If this is used - we should have a variable to allow disabling it.

when: arc_frontend_nis

**Comment by A1ve5** [comment]
Like this?

In group_vars/grid/grid.yml
arc_frontend_nis: true 

and

- name: Update NIS DB
  command: /usr/bin/make -C /var/yp
  delegate_to: install
  when: arc_frontend_nis

**Comment by martbhell** [comment]
And to false in defaults

**Comment by martbhell** [comment]
Nice move with delegate btw :)

**Comment by A1ve5** [comment]
thanks :)
Solved on e0c09dea1491448f45c4bffd35fd9d3552f4483e
